# Generated by Django 4.2.26 on 2025-12-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_recipe_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="description",
        ),
    ]
