# Generated by Django 4.2.26 on 2025-12-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_recipe_author"),
        ("author", "0003_remove_author_cookbooks_remove_author_recipes"),
        ("cookbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookbook",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cookbooks",
                to="author.author",
            ),
        ),
        migrations.AlterField(
            model_name="cookbook",
            name="recipes",
            field=models.ManyToManyField(
                blank=True, related_name="cookbooks", to="recipe.recipe"
            ),
        ),
    ]
