# Generated by Django 4.2.26 on 2025-12-03 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "__first__"),
        ("cookbook", "0001_initial"),
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="cookbooks",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cookbook.cookbook"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="recipes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recipe.recipe"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
