# Generated by Django 4.2.26 on 2025-12-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="cookbooks",
        ),
        migrations.RemoveField(
            model_name="author",
            name="recipes",
        ),
    ]
