# Generated by Django 4.2.26 on 2025-12-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                (
                    "recipes",
                    models.ManyToManyField(
                        related_name="ingredients", to="recipe.recipe"
                    ),
                ),
            ],
        ),
    ]
